services:
  app_myduckduckapi:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: package.json
          target: /functions/package.json
        - action: rebuild
          path: package-lock.json
          target: /functions/package-lock.json
        - action: sync+restart
          path: ./
          target: /functions
    environment:
      DUCKDB_PATH: $APP_MYDUCKDUCKAPI_DUCKDB_PATH
      FEATURE_MIN_INSTANCES: $APP_MYDUCKDUCKAPI_FEATURE_MIN_INSTANCES
      FEATURE_PERSISTENT_DATA: $APP_MYDUCKDUCKAPI_FEATURE_PERSISTENT_DATA
      HASURA_SERVICE_TOKEN_SECRET: $APP_MYDUCKDUCKAPI_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MYDUCKDUCKAPI_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MYDUCKDUCKAPI_OTEL_SERVICE_NAME
      ZENDESK_CLIENT_ID: $APP_MYDUCKDUCKAPI_ZENDESK_CLIENT_ID
      ZENDESK_CLIENT_SECRET: $APP_MYDUCKDUCKAPI_ZENDESK_CLIENT_SECRET
      ZENDESK_PKCE_REQUIRED: $APP_MYDUCKDUCKAPI_ZENDESK_PKCE_REQUIRED
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6514:8080
